# Generated by Django 5.0.6 on 2024-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('number_of_people', models.PositiveIntegerField()),
                ('specific_needs', models.TextField(blank=True)),
                ('frequency_of_service', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HouseHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('job_titles', models.CharField(max_length=200)),
                ('experience', models.TextField()),
                ('references', models.TextField(blank=True)),
                ('availability', models.CharField(max_length=100)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('background_check', models.FileField(blank=True, null=True, upload_to='background_checks/')),
            ],
        ),
    ]
