# Generated by Django 5.0.6 on 2024-06-23 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accnt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.AddField(
            model_name='househelp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='househelp',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='househelp',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='househelp',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='househelp',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='background_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='job_titles',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='references',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
