# Generated by Django 5.0.6 on 2024-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accnt', '0003_alter_househelp_options_househelp_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='househelp',
            options={},
        ),
        migrations.RemoveField(
            model_name='employer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='househelp',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='househelp',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='househelp',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='househelp',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='househelp',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='employer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employer',
            name='frequency_of_service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='employer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to='profile_pictures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='specific_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='background_check',
            field=models.FileField(blank=True, upload_to='background_checks/'),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='job_titles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to='profile_pictures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='househelp',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
