# Generated by Django 5.0.6 on 2024-06-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accnt', '0004_alter_employer_options_alter_househelp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
